---
- name: Execute netstat on webservers
  hosts: webservers
  become: yes
  
  tasks:
    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools

    - name: Run netstat command
      become: true
      command: netstat -tupln
      register: netstat_output

    - name: Display netstat results
      debug:
        var: netstat_output.stdout_lines

