---
- name: Add 4GB Swap for Webserver Hosts
  hosts: webservers
  become: true

  tasks:
    - name: Create swap file if not exists
      command: fallocate -l 4G /swapfile
      args:
        creates: /swapfile

    - name: Set permissions on swap file
      command: chmod 600 /swapfile

    - name: Make swap space
      command: mkswap /swapfile

    - name: Enable swap
      command: swapon /swapfile
      args:
        creates: /swapfile

    - name: Add swap entry to fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present

