---
- name: Execute netstat on webservers
  hosts: webservers
  gather_facts: true
  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest

    - name: Install net-tools
      package:
        name: net-tools
        state: present

    - name: Run netstat command
      become: true
      command: netstat -tupln
      register: netstat_output

    - name: Display netstat results
      debug:
        var: netstat_output.stdout_lines

