---
- name: Add 4GB Swap for Webserver Hosts
  hosts: webservers
  become: true

  tasks:
    - name: Create swap file if not exists
      become: true
      command: fallocate -l 4G /swapfile

    - name: Set permissions on swap file
      become: true
      command: chmod 600 /swapfile

    - name: Make swap space
      become: true
      command: mkswap /swapfile

    - name: Enable swap
      become: true
      command: swapon /swapfile

    - name: Add swap entry to fstab
      become: true
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present

